data: ./data/svhn
batch_size: 128
test_batch_size: 1000
epochs: 160
lr: 0.01
momentum: 0.9
no_cuda: False
seed: 1
log_interval: 10
optim: sgd
arch: cnn
workers: 12
weight_decay: 5.e-4
train_accuracy: True
lr_decay_epoch: 80,120
num_class: 10
