data: none
batch_size: 64
test_batch_size: 1000
epochs: 50
lr: 0.01
momentum: 0.5
no_cuda: False
seed: 1
log_interval: 10
optim: sgd
arch: None
workers: 2
weight_decay: 5.e-4
num_train_data: 640
num_test_data: 10000
dim: 2
c_const: 50
d_const: 10
train_accuracy: True
lr_decay_epoch: 100
num_class: 5
