data: ./data/mnist
batch_size: 128
test_batch_size: 1000
epochs: 50
lr: 0.01
momentum: 0.5
no_cuda: False
seed: 1
log_interval: 10
optim: sgd
arch: mlp
workers: 10
weight_decay: 5.e-4
train_accuracy: True
lr_decay_epoch: 30
num_class: 10
